### ISSUE TITLE
compute_entropy function not used?

### ISSUE THREAD

**Issue by ramchalamkr** [hongzimao/a3c#1]
In the a3c.py, there is a function compute_entropy(x) which is actually not called anywhere.
Is it something that needs to be used somewhere or am I missing something?

Thanks

**Comment by hongzimao** [comment]
It is used as an auxiliary function somewhere else. For example, when we use this tool for a video streaming project: https://github.com/hongzimao/pensieve

In the code, however, the entropy computation in the loss is here: https://github.com/hongzimao/a3c/blob/master/a3c.py#L51-L52.

**Comment by ramchalamkr** [comment]
Thank you!
